# For more info on HTTP files go to https://aka.ms/vs/httpfile

### Get all tasks

GET http://localhost:5078/tasks

### Post task 1

POST http://localhost:5078/tasks
content-type: application/json

{
  "Name": "Write Demo",
  "DueDate": "2026-06-21",
  "IsCompleted": false,
  "ProjectId": null
}

### Post task 2

POST http://localhost:5078/tasks
content-type: application/json
{

  "Name": "Write Demo 2",
  "DueDate": "2026-06-26",
  "IsCompleted": false,
  "ProjectId": null
}


### Post task 3

POST http://localhost:5078/tasks
Content-Type: application/json

{
  "Name": "Write Demo",
  "DueDate": "2026-06-21",
  "IsCompleted": false,
  "ProjectId": null
}


### Get Task 2

GET http://localhost:5078/tasks/2

### Delete

DELETE http://localhost:5078/tasks/2



### Redirect GET

GET http://localhost:5078/todos/1


### Endpoint filter past due

POST http://localhost:5078/tasks
content-type: application/json
{
    "Name": "Endpoint past",
    "DueDate": "2025-06-01",
    "IsCompleted": false,
    "ProjectId": null
}

### Endpoint filter completed

POST http://localhost:5078/tasks
content-type: application/json
{
    "Name": "Redirect Demo ",
    "DueDate": "2025-06-21",
    "IsCompleted": true,
    "ProjectId": null
}

### Endpoint filter past due

POST http://localhost:5078/tasks
content-type: application/json
{
    "Name": "Redirect Demo ",
    "DueDate": "2025-06-01",
    "IsCompleted": true,
    "ProjectId": null
}

